"project_id": "574147"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
"api_token_env": "CROWDIN_TOKEN"

files:
  [
    {
      "source": "/src/translations/nb.json",
      "translation": "/src/translations/%two_letters_code%.json",
      "dest": "/02-pc23-greeting/nb.json",
      "export_only_approved": false,
      "skip_untranslated_strings": false,
    },
  ]
